version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: deploy/api/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - shared_images:/deploy/images
    environment:
      - UPLOAD_URL=http://fastapi:8000/upload
      - ATTACK_URL=http://fastapi:8000/attack/
      - DEFEND_URL=http://fastapi:8000/defend/
      - PREDICT_URL=http://fastapi:8000/inference/
      - ENV_TYPE=docker

  streamlit:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - shared_images:/deploy/images
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared_images: