from defences.median_filter import median_filter_defend_image_from_path as median_filter
from defences.thresholding import thresholding_defend_image_from_path as thresholding
from defences.gradient_transform import gradient_transform_defend_image_from_path as gradient_transform
from defences.identity import Identity
